const recipes = [
    {
        date_created: "11-7-2025",
        title: "title",
        creator_name: "example name",
        creator_user_id: 1,
        body: "description",
        img: "recipe.png",
        recipe_id: 1,
    },
    {
        date_created: "11-7-2025",
        title: "title",
        creator_name: "example name",
        creator_user_id: 2,
        body: "description",
        img: "recipe.png",
        recipe_id: 2,
    },
    {
        date_created: "11-7-2025",
        title: "title",
        creator_name: "example name",
        creator_user_id: 3,
        body: "description",
        img: "recipe.png",
        recipe_id: 3,
    },
    {
        date_created: "11-7-2025",
        title: "title",
        creator_name: "example name",
        creator_user_id: 4,
        body: "description",
        img: "recipe.png",
        recipe_id: 4,
    },
    {
        date_created: "11-7-2025",
        title: "title",
        creator_name: "example name",
        creator_user_id: 5,
        body: "description",
        img: "recipe.png",
        recipe_id: 5,
    },
    {
        date_created: "11-7-2025",
        title: "title",
        creator_name: "example name",
        creator_user_id: 5,
        body: "description",
        img: "recipe.png",
        recipe_id: 6,
    },
    {
        date_created: "11-7-2025",
        title: "title",
        creator_name: "example name",
        creator_user_id: 5,
        body: "description",
        img: "recipe.png",
        recipe_id: 7,
    },
    {
        date_created: "11-7-2025",
        title: "title",
        creator_name: "example name",
        creator_user_id: 5,
        body: "description",
        img: "recipe.png",
        recipe_id: 8,
    },
]

export default recipes;